# Generated by Django 6.0.3 on 2026-04-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_department_user_remember_last_scope_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name="Approuvé par l'administrateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ROLE_1', 'Role 1'), ('ROLE_2', 'Role 2'), ('ROLE_3', 'Role 3'), ('ADMIN', 'Administrateur')], max_length=20, null=True, verbose_name='Rôle'),
        ),
    ]
