# Generated by Django 6.0.3 on 2026-05-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0006_alter_parttechnicaldata_multisourcing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_number', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(choices=[('selective', 'Selective Switch'), ('full', 'Full Switch')], max_length=20)),
                ('full_switch', models.BooleanField(default=False)),
                ('purchase_region', models.CharField(max_length=50)),
                ('usage_market', models.CharField(max_length=50)),
                ('total_annual_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_saving', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('release_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_concentration_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_current', to='component.parttechnicaldata')),
                ('target_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_target', to='component.parttechnicaldata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('delta_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('annual_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_saving', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('business_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business_case.businesscase')),
                ('current_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_items_current', to='component.parttechnicaldata')),
                ('target_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_items_target', to='component.parttechnicaldata')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('owner', models.CharField(choices=[('Engineering', 'Engineering'), ('Procurement', 'Procurement'), ('Program', 'Program'), ('Quality', 'Quality'), ('Customer', 'Customer')], default='Engineering', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='business_case.businesscase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
