# Generated by Django 6.0.3 on 2026-05-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscaseitem',
            name='business_case',
        ),
        migrations.RemoveField(
            model_name='businesscasetask',
            name='business_case',
        ),
        migrations.RemoveField(
            model_name='businesscaseitem',
            name='current_part',
        ),
        migrations.RemoveField(
            model_name='businesscaseitem',
            name='target_part',
        ),
        migrations.DeleteModel(
            name='BusinessCase',
        ),
        migrations.DeleteModel(
            name='BusinessCaseTask',
        ),
        migrations.DeleteModel(
            name='BusinessCaseItem',
        ),
    ]
