# Generated by Django 6.0.3 on 2026-04-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartTechnicalData',
            fields=[
                ('leoni_part_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fors_material_group', models.CharField(blank=True, max_length=100, null=True)),
                ('fors_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('s4_description', models.TextField(blank=True, null=True)),
                ('supplier_group', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('multisourcing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('compatibility_status', models.CharField(blank=True, max_length=50, null=True)),
                ('multisourcing_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_recent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartTransportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokid', models.CharField(max_length=100)),
                ('location_region', models.CharField(max_length=100)),
                ('annual_volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_receipts', to='component.parttechnicaldata')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_receipts', to='component.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='PartProjectUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokid', models.CharField(max_length=100)),
                ('oem_brand', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('monthly_sum_volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usages', to='component.parttechnicaldata')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usages', to='component.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='PartPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=100)),
                ('price_date', models.DateField()),
                ('full_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='component.parttechnicaldata')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='component.uploadbatch')),
            ],
        ),
    ]
