# Generated by Django 6.0.3 on 2026-04-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_partprice_imported_at_partprojectusage_imported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttransportreceipt',
            name='location_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
