# Generated by Django 6.0.3 on 2026-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_parttransportreceipt_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='partprice',
            name='lokid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
