# Generated by Django 6.0.3 on 2026-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_partprice_lokid'),
    ]

    operations = [
        migrations.AddField(
            model_name='partprice',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
