# Generated by Django 6.0.3 on 2026-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_partprice_price_eur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttechnicaldata',
            name='multisourcing_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
