# Generated by Django 6.0.3 on 2026-04-17 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0002_partprice_imported_at_partprojectusage_imported_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('filename_tech', models.CharField(blank=True, max_length=255, null=True)),
                ('filename_transport', models.CharField(blank=True, max_length=255, null=True)),
                ('filename_project', models.CharField(blank=True, max_length=255, null=True)),
                ('filename_prices', models.CharField(blank=True, max_length=255, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='component.uploadbatch')),
            ],
        ),
    ]
