# Generated by Django 6.0.3 on 2026-04-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='duplicates_removed',
            field=models.IntegerField(default=0, help_text='Doublons supprimés'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Durée totale en secondes'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='error_count',
            field=models.IntegerField(default=0, help_text="Nombre d'erreurs"),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='imported_rows',
            field=models.IntegerField(default=0, help_text='Lignes importées avec succès'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='rows_after_clean',
            field=models.IntegerField(default=0, help_text='Lignes après nettoyage'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='rows_read',
            field=models.IntegerField(default=0, help_text='Lignes lues avant nettoyage'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='total_null_count',
            field=models.IntegerField(default=0, help_text='Valeurs nulles trouvées'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='warning_count',
            field=models.IntegerField(default=0, help_text='Nombre de warnings'),
        ),
    ]
