# Generated by Django 6.0.3 on 2026-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_importhistory_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='import_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
