# Generated by Django 6.0.3 on 2026-05-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0003_importhistory_import_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_number', models.CharField(max_length=100)),
                ('current_part', models.CharField(blank=True, max_length=100, null=True)),
                ('target_part', models.CharField(blank=True, max_length=100, null=True)),
                ('scenario_type', models.CharField(choices=[('selective', 'Selective Switch'), ('full', 'Full Switch')], max_length=20)),
                ('full_switch', models.BooleanField(default=False)),
                ('purchase_region', models.CharField(max_length=50)),
                ('usage_market', models.CharField(max_length=50)),
                ('notes_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='saved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='importhistory',
            name='import_started_at',
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='duplicates_removed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='imported_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='rows_after_clean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='rows_read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='total_null_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='warning_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BusinessCaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('ONGOING', 'Ongoing'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('owner', models.CharField(choices=[('Engineering', 'Engineering'), ('Procurement', 'Procurement'), ('Program', 'Program'), ('Quality', 'Quality'), ('Customer', 'Customer')], default='Engineering', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='historique.businesscase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
